### ISSUE TITLE
P8 Bluetooth Antenna Information?

### ISSUE THREAD

**Issue by bobpaul** [enaon/eucWatch#5]
The README mentions that it's extremely likely that the P8 watches will require antenna replacement. Can you provide any information on this? I've been searching off and on for the past couple of days and haven't found anything beyond instructions on opening it up. 

Does anyone know where there's more information on this? I think it would be really good to get a link to a tutorial or something into the README

**Comment by enaon** [comment]
I am afraid that I haven't any good pictures with it, I will take sme next time I happen to open one up. A length of 6cm long piece of wire solid or twisted is a good length. It can be run the way the original antenna was, then along the battery then almost to the button. Here is one, but I was demonstrating something else and the antenna was moved up, so it is hard to see well. 

Some wheels like the z10 do not need an antenna change, and it also depends on the watch, new ones are better I think, maybe you will not need it. 

![image](https://user-images.githubusercontent.com/12843480/114835631-723d8d80-9dda-11eb-9e77-40044073f263.png)

**Comment by bobpaul** [comment]
I just received a Ton5 variant watch and have flashed it successfully. I'm able to connect to my mTen3 from almost as far away as my phone.

But just cause I'm a curious type, I'm looking at [a youtube teardown video](https://www.youtube.com/watch?v=ox1SoyKn7zs) and comparing to your photo. (In the video he added some other wires so he can flash and charge the watch with the back removed.)

Have I highlighted the bluetooth antenna wire in yellow?
![image](https://user-images.githubusercontent.com/90864/115603907-576d8c00-a2a6-11eb-8717-94f28d634cc7.png)

**Comment by enaon** [comment]
Yes, it is the on in yellow. Yours seem a bit too long, maybe trimm 1-2 mm as a test too if you like. 

It does work very will indoors, I may have gave the wrong impression with the warning in the antenna. It's not like the P8 has a bad BT coverage, it is very good, this is why I recommend it over the DK08, that works too. It is just that I use it for haptic feedback, I want it to be perfect, not just good.  

You will find that indoors test are different from oudoors conditions. Maybe general noise, signal lost due to open space, motor noise, all that takes a toll. You may try the following if you like, 6cm long cable, placed like in one of two shapes. 

![115603907-576d8c00-a2a6-11eb-8717-94f28d634cc7](https://user-images.githubusercontent.com/12843480/115635123-a69dd600-a313-11eb-8d71-64a95a5e69db.png)

**Comment by enaon** [comment]
in any case, the watch will work better that we are used to with the android BT experience. I guess android is doing something wrong, but espruino never looses the connection, and if so, it takes 0.5 sec to reconnect, just point the watch to the wheel and that is it. 

So yes, the antenna is important if one relies on real time haptic feedback like I do, but f one just needs a dash, it is excellent as it stands.

**Comment by bobpaul** [comment]
Oh, that's good info!

And I guess (a bit off topic for this issue) that's why the watch does EUC emulation rather than just acting as a remote display for EUC World or Wheellogger. As I think about it a bit more, this is definitely the way to go. If someone has a low-spec android phone, there's always risk that the logger app might get killed due to out of memory when you receive a phone call, SMS, etc during a ride. If the watch is the bridge, it keeps working even if the phone gaps out.
