### ISSUE TITLE
how to connect the Gadgetbridge app

### ISSUE THREAD

**Issue by tyrone1984** [enaon/eucWatch#6]
@enaon can you tell me how to connect the Gadgetbridge app via the bluetooth?
thax!

**Comment by enaon** [comment]
sure.

The gadgetbridge(GB) filters espruino devices by name, it looks for bangle.js or puck.js  or espruino in the device name.  

You can either change the name of your p8 to one of the above, or use dev-mode to make GB find the watch one time only, and it will then remember it regardless of the name.

To enter dev-mode, do an up-getsture to get to settings, then press the info icon on center-bottom, and then long-hold or restart. 

The watch will buzz and the screen will go black. Scan for the watch from GB, connect (dont pair) and then tap once on the side button. The watch will restart, and GB will still connect from now on. 
 

Make sure the GB icon is enabled on the BT settings menu. Do a restart( using settings-info-restart) if you enable it, so that settings are saved. 

You can toggle the GB connection from the GB icon on BT settings on the watch, and use the Find my phone icon from settings when connected.

**Comment by enaon** [comment]
Some more notes, until I make a small manual :)

Having the BT connected will take the standby from a month down to a week. 
The Tx power can be set, and it relates to drain, better keep it to the lowest you feel is ok for the phone. 
When connected to the EUC, it will auto max, and will get back the one in the settings when disconnected. 

To set the tx power, long hold on the BT icon, inside the BT menu. You will notice 1,2 or 3 little bars, changing, 
3 bars are +4dBm, 1 bar is -4dBm.

**Comment by tyrone1984** [comment]
;-) Great fake!
